apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hotel-management.fullname" . }}
  labels:
    app: {{ include "hotel-management.name" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "hotel-management.fullname" . }}
            port:
              number: 80

