apiVersion: v1
kind: Service
metadata:
  name: {{ include "hotel-management.fullname" . }}
  labels:
    app: {{ include "hotel-management.name" . }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ include "hotel-management.name" . }}

